-- ============================================
-- D-KRAFT ERP - EXECUTE THIS SQL IN SUPABASE
-- Copy ALL of this and run in SQL Editor
-- https://supabase.com/dashboard/project/qalqscfrcxzzvrcvqqbp/sql/new
-- ============================================

-- CLIENTS
ALTER TABLE clients ADD COLUMN IF NOT EXISTS code VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS company_name VARCHAR(200);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS contact_name VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS contact VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS company VARCHAR(200);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS zip VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'México';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS tax_id VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS rfc VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS website VARCHAR(200);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS billing_entity VARCHAR(20) DEFAULT 'DOVECREEK';

-- SUPPLIERS
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS company_name VARCHAR(200);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact_name VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS zip VARCHAR(20);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS country VARCHAR(100) DEFAULT 'México';
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS tax_id VARCHAR(20);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS rfc VARCHAR(20);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS website VARCHAR(200);

-- MATERIALS
ALTER TABLE materials ADD COLUMN IF NOT EXISTS category_id UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS categoryId UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS unit_id UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS unitId UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS supplier_id UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS supplierId UUID;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(12,4) DEFAULT 0;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS stock DECIMAL(12,4) DEFAULT 0;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS min_stock DECIMAL(12,4) DEFAULT 0;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS max_stock DECIMAL(12,4);
ALTER TABLE materials ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
ALTER TABLE materials ADD COLUMN IF NOT EXISTS description TEXT;

-- PRODUCTS
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id UUID;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_id UUID;
ALTER TABLE products ADD COLUMN IF NOT EXISTS base_price DECIMAL(12,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price DECIMAL(12,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;

-- OPERATIONS - Critical for work orders
ALTER TABLE operations ADD COLUMN IF NOT EXISTS work_order_number VARCHAR(50);
ALTER TABLE operations ADD COLUMN IF NOT EXISTS project_id UUID;
ALTER TABLE operations ADD COLUMN IF NOT EXISTS name VARCHAR(200);
ALTER TABLE operations ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'Medium';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE operations ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0;
ALTER TABLE operations ADD COLUMN IF NOT EXISTS current_stage VARCHAR(50);
ALTER TABLE operations ADD COLUMN IF NOT EXISTS assigned_divisions JSONB DEFAULT '[]';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS stages JSONB DEFAULT '{}';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE operations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE operations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- PROJECTS
ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_id UUID;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS quotation_id UUID;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deadline DATE;

-- QUOTATIONS
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS client_id UUID;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS folio VARCHAR(50);
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS tax DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS total DECIMAL(12,2) DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS billing_entity VARCHAR(20) DEFAULT 'DOVECREEK';

-- REQUISITIONS
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS client_id UUID;
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS quotation_id UUID;
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS folio VARCHAR(50);
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS subtotal DECIMAL(12,2) DEFAULT 0;
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS tax DECIMAL(12,2) DEFAULT 0;
ALTER TABLE requisitions ADD COLUMN IF NOT EXISTS total DECIMAL(12,2) DEFAULT 0;

-- PROFILES (Staff)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS employee_id VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS position VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hire_date DATE;

-- Create categories table if not exists
CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create units table if not exists
CREATE TABLE IF NOT EXISTS units (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL,
    abbreviation VARCHAR(10),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create activity_log table if not exists
CREATE TABLE IF NOT EXISTS activity_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50),
    entity_id TEXT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';

SELECT 'SUCCESS! All columns added. Refresh dkraft.com.mx' as result;
